### ISSUE TITLE
Add nbdime to python environment

### ISSUE THREAD

**Issue by tpanza** [UCB-w261/w261-environment#14]
Please consider adding the nbdime package to the Python environment on Altiscale.

http://nbdime.readthedocs.io/en/stable/index.html

It has nice features for diffing and merging Jupyter notebooks, which is critical for team projects.

**Comment by jameswinegar** [comment]
The environment was changed to jupyterlab last night since there was some dependency failures, and looking at the past issues on that it doesn't play nicely with jupyterlab yet. I like the project though.

**Comment by tpanza** [comment]
Does jupyterlab include an ability to diff and merge ipynb files?
