### ISSUE TITLE
allocating CPUs and RAM on macOS

### ISSUE THREAD

**Issue by jrtuenge** [UCB-w261/w261-environment#28]
Is the text "Click Docker in the clock(?) area" referring to the menu bar? 
https://support.apple.com/guide/mac-help/menu-bar-mchlp1446/mac
Also FYI, it's under Preferences, rather than Settings:
![Screen Shot 2019-05-11 at 4 58 53 PM (2)](https://user-images.githubusercontent.com/31391264/57576164-9930ff00-740e-11e9-80b2-72813f6ca979.png)

**Comment by sartaj10** [comment]
Yes, i think that's what they mean by this.
